### ISSUE TITLE
Zipped file means obfuscated code

### ISSUE THREAD

**Issue by BasedAnon** [JAMadison/Prompt_Reveal#1]
I'm not downloading this:  you put it in a zip, so I can't review the code.
Is it malware?

**Comment by BasedAnon** [comment]
We're all learning, I'm a beginner myself, just wanted to make it clear I wasn't intending to come off as hostile.

**Comment by JAMadison** [comment]
Hi Based, you didn't come off as hostile at all. That is for people who don't know how to run python code. https://github.com/JAMadison/Prompt_Reveal/blob/main/main.py - is the whole script :)

**Comment by JAMadison** [comment]
https://github.com/JAMadison/Prompt_Reveal - There are now 3 options for running Prompt Reveal - I will update the repository with instructions/ability to use this in a local Python environment.
